models:
  - name: dim_customers
    description: "Customer dimension table"
    columns:
      - name: customer_key
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null

  - name: dim_products
    description: "Product dimension"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
  - name: dim_sellers
    description: "Seller dimension"
    columns:
      - name: seller_id
        tests:
          - not_null
          - unique
  - name: dim_date
    description: "Date dimension"
    columns:
      - name: date_day
        tests:
          - not_null
          - unique
  - name: fact_sales # here we ensure referential integrity
    description: "Sales fact table at order-product grain"
    columns:
      - name: order_id
        tests:
          - not_null

      - name: customer_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_key

      - name: product_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_id

      - name: seller_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_sellers')
                field: seller_id

      - name: order_date
        tests:
          - relationships:
              arguments:
                to: ref('dim_date')
                field: date_day