models:
  - name: stg_customers
    description: "Cleaned customer data from Olist"
    columns:
      - name: customer_id
        tests:
          - not_null

      - name: customer_unique_id
        tests:
          - not_null

  - name: stg_orders
    description: "Cleaned order-level data"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null

  - name: stg_orderitems
    description: "Order line items"
    columns:
      - name: order_id
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null
