version: 2

sources:
  - name: raw
    database: SALES_ANALYTICS
    schema: RAW
    tables:
      - name: CUSTOMERS
      - name: ORDERS
      - name: ORDERITEMS
      - name: ORDERPAYMENTS
      - name: PRODUCTS
      - name: SELLERS
      - name: REVIEWS
      - name: GEOLOCATION
      - name: TRANSLATION
